name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      RUBY_VERSION: '2.5.x'

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
    - name: Install gems
      run: gem install mdl
    - name: Run Markdown Lint
      run: mdl --git-recurse .

  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: TEST
      run: echo $PATH

    # - name: Mock binaries
    #   run: |
    #     # Replace some binaries with a script that exits quickly, otherwise the Travis build will time out or fail.
    #     mkdir $HOME/bin

    #     printf '#!'"/usr/bin/env bash\necho 'mas is overridden to allow Travis build to succeed.'" > $HOME/bin/mas
    #     chmod +x $HOME/bin/mas
    # - name: Run make
    #   run: make
