name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install gems
      run: gem install mdl
    - name: Run Markdown Lint
      run: mdl --git-recurse .

  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run make
      run: make
